language: node_js
os: linux
dist: xenial
node_js:
  - '16'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g pnpm
install:
  - pnpm i
script:
  - pnpm test
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
  - pnpm build:pages
  - echo "json-diff-kit.js.org" > docs/CNAME
  - git add -A
  - git commit -m Pages
deploy:
  strategy: git
  provider: pages
  cleanup: false
  keep_history: true
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
